# Generated by Django 5.0 on 2024-01-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_author"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="author",),
    ]
